# VideoGenius 文档自动化维护系统配置文件

[monitoring]
# 文档检查间隔（秒）
check_interval = 3600  # 每小时检查一次

# 备份间隔（秒）
backup_interval = 86400  # 每天备份一次

# 监控的文档列表
monitored_docs = [
    "README.md",
    "docs/development/VideoGenius全面发展计划.md",
    "docs/管理规范/项目状态总览.md",
    "docs/user/启动说明.md",
    "docs/user/智能启动工具使用说明.md",
    "docs/ai_assistant/记忆恢复指南.md",
    "docs/ai_assistant/AI助手承诺追踪系统.md",
    "docs/ai_assistant/AI助手记忆存储.md"
]

[quality]
# 文档最大过期天数
max_doc_age_days = 7

# 最小更新间隔（秒）
min_update_interval = 3600  # 1小时

# 文档新鲜度阈值
freshness_thresholds = { aging = 24, outdated = 168 }  # 小时

[backup]
# 备份保留天数
retention_days = 30

# 备份目录
backup_dir = "backups"

# 自动清理旧备份
auto_cleanup = true

[notifications]
# 启用通知
enable_alerts = true

# 通知渠道
alert_channels = ["console", "log", "file"]

# 日志级别
log_level = "INFO"

# 日志文件路径
log_file = "logs/doc_automation.log"

[schedule]
# 每日任务执行时间
daily_time = "09:00"

# 每周任务执行时间（周一）
weekly_time = "09:00"

# 每月任务执行日期
monthly_day = 1

[reports]
# 报告保存目录
report_dir = "logs"

# 报告保留天数
report_retention_days = 90

# 自动生成报告
auto_generate = true

# 报告格式
report_format = "markdown"

[ai_assistant]
# AI助手工作模式
work_mode = "autonomous"  # autonomous, interactive, manual

# 自动更新AI记忆
auto_update_memory = true

# 记忆备份频率
memory_backup_frequency = "daily"

# 最大记忆文件大小（MB）
max_memory_size = 10

[optimization]
# 启用自动优化
enable_auto_optimization = true

# 优化检查间隔（天）
optimization_interval = 7

# 性能监控
enable_performance_monitoring = true

# 用户反馈收集
collect_user_feedback = true 