version: '3.8'
x-common-volumes: &common-volumes
  - ./:/VideoGenius

services:
  webui:
    build: .
    volumes:
      - ./:/VideoGenius
    ports:
      - "8501:8501"
    container_name: "videogenius-webui"
    command: ["python", "-m", "streamlit", "run", "webui/Main.py", "--server.address=0.0.0.0", "--server.port=8501", "--browser.gatherUsageStats=false"]

  api:
    build: .
    volumes:
      - ./:/VideoGenius
    ports:
      - "8080:8080"
    container_name: "videogenius-api"
    command: ["python", "main.py"]