[browser]
gatherUsageStats = false

[theme]
# VideoGenius现代化主题配置
primaryColor = "#FF6B6B"              # 主要颜色 - 活力红
backgroundColor = "#0E1117"           # 背景颜色 - 深蓝黑
secondaryBackgroundColor = "#1E2329"  # 次要背景 - 深灰蓝  
textColor = "#FAFAFA"                 # 文字颜色 - 浅白
font = "sans serif"                   # 字体

[server]
# 性能优化配置
maxUploadSize = 500                   # 最大上传文件500MB
enableCORS = false                    # 跨域设置
enableXsrfProtection = false          # XSRF保护

[client]
# 界面响应优化
showErrorDetails = true               # 显示详细错误信息
toolbarMode = "minimal"               # 最小化工具栏